apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:12
      env:
        - name: POSTGRES_PASSWORD
          value: password
      ports:
        - containerPort: 5432
          name: postgres
      volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-persistent-storage
      persistentVolumeClaim:
        claimName: postgres-pvc
